// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fNull
static double fNull(double a);
RcppExport SEXP _rtp_fNull(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fNull(a));
    return rcpp_result_gen;
END_RCPP
}
// init
double init(double k, NumericVector p);
RcppExport SEXP _rtp_init(SEXP kSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(init(k, p));
    return rcpp_result_gen;
END_RCPP
}
// betaSD
static double betaSD(double a, double b);
RcppExport SEXP _rtp_betaSD(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(betaSD(a, b));
    return rcpp_result_gen;
END_RCPP
}
// dbetaHight
double dbetaHight(double a, double b);
RcppExport SEXP _rtp_dbetaHight(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(dbetaHight(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fBetaD
double fBetaD(double b);
RcppExport SEXP _rtp_fBetaD(SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fBetaD(b));
    return rcpp_result_gen;
END_RCPP
}
// fGammaD
double fGammaD(double g);
RcppExport SEXP _rtp_fGammaD(SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(fGammaD(g));
    return rcpp_result_gen;
END_RCPP
}
// fBetaQ
double fBetaQ(double p);
RcppExport SEXP _rtp_fBetaQ(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(fBetaQ(p));
    return rcpp_result_gen;
END_RCPP
}
// fGammaQ
double fGammaQ(double p);
RcppExport SEXP _rtp_fGammaQ(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(fGammaQ(p));
    return rcpp_result_gen;
END_RCPP
}
// fBetaDtop
double fBetaDtop();
RcppExport SEXP _rtp_fBetaDtop() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(fBetaDtop());
    return rcpp_result_gen;
END_RCPP
}
// probSmallest
static double probSmallest(NumericVector p);
RcppExport SEXP _rtp_probSmallest(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(probSmallest(p));
    return rcpp_result_gen;
END_RCPP
}
// fisher
static double fisher(NumericVector p);
RcppExport SEXP _rtp_fisher(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(fisher(p));
    return rcpp_result_gen;
END_RCPP
}
// riemannBeta
double riemannBeta(double k, NumericVector p, double tol, double stepscale);
RcppExport SEXP _rtp_riemannBeta(SEXP kSEXP, SEXP pSEXP, SEXP tolSEXP, SEXP stepscaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type stepscale(stepscaleSEXP);
    rcpp_result_gen = Rcpp::wrap(riemannBeta(k, p, tol, stepscale));
    return rcpp_result_gen;
END_RCPP
}
// simpsonAdaBeta
double simpsonAdaBeta(double k, NumericVector p, double abstol, double reltol);
RcppExport SEXP _rtp_simpsonAdaBeta(SEXP kSEXP, SEXP pSEXP, SEXP abstolSEXP, SEXP reltolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< double >::type reltol(reltolSEXP);
    rcpp_result_gen = Rcpp::wrap(simpsonAdaBeta(k, p, abstol, reltol));
    return rcpp_result_gen;
END_RCPP
}
// riemannGamma
double riemannGamma(double k, NumericVector p, double tol, double stepscale);
RcppExport SEXP _rtp_riemannGamma(SEXP kSEXP, SEXP pSEXP, SEXP tolSEXP, SEXP stepscaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type stepscale(stepscaleSEXP);
    rcpp_result_gen = Rcpp::wrap(riemannGamma(k, p, tol, stepscale));
    return rcpp_result_gen;
END_RCPP
}
// simpsonGamma
double simpsonGamma(double k, NumericVector p, double tol, double stepscale);
RcppExport SEXP _rtp_simpsonGamma(SEXP kSEXP, SEXP pSEXP, SEXP tolSEXP, SEXP stepscaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type stepscale(stepscaleSEXP);
    rcpp_result_gen = Rcpp::wrap(simpsonGamma(k, p, tol, stepscale));
    return rcpp_result_gen;
END_RCPP
}
// tfisher
double tfisher(double lw, double n, double tau1, double tau2, double tol);
RcppExport SEXP _rtp_tfisher(SEXP lwSEXP, SEXP nSEXP, SEXP tau1SEXP, SEXP tau2SEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lw(lwSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type tau1(tau1SEXP);
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(tfisher(lw, n, tau1, tau2, tol));
    return rcpp_result_gen;
END_RCPP
}
// uniSel
int uniSel(int k, NumericVector p);
RcppExport SEXP _rtp_uniSel(SEXP kSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(uniSel(k, p));
    return rcpp_result_gen;
END_RCPP
}
// simpleSel
int simpleSel(int k, NumericVector p);
RcppExport SEXP _rtp_simpleSel(SEXP kSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(simpleSel(k, p));
    return rcpp_result_gen;
END_RCPP
}
// nth_element
int nth_element(int k, NumericVector p);
RcppExport SEXP _rtp_nth_element(SEXP kSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(nth_element(k, p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rtp_fNull", (DL_FUNC) &_rtp_fNull, 1},
    {"_rtp_init", (DL_FUNC) &_rtp_init, 2},
    {"_rtp_betaSD", (DL_FUNC) &_rtp_betaSD, 2},
    {"_rtp_dbetaHight", (DL_FUNC) &_rtp_dbetaHight, 2},
    {"_rtp_fBetaD", (DL_FUNC) &_rtp_fBetaD, 1},
    {"_rtp_fGammaD", (DL_FUNC) &_rtp_fGammaD, 1},
    {"_rtp_fBetaQ", (DL_FUNC) &_rtp_fBetaQ, 1},
    {"_rtp_fGammaQ", (DL_FUNC) &_rtp_fGammaQ, 1},
    {"_rtp_fBetaDtop", (DL_FUNC) &_rtp_fBetaDtop, 0},
    {"_rtp_probSmallest", (DL_FUNC) &_rtp_probSmallest, 1},
    {"_rtp_fisher", (DL_FUNC) &_rtp_fisher, 1},
    {"_rtp_riemannBeta", (DL_FUNC) &_rtp_riemannBeta, 4},
    {"_rtp_simpsonAdaBeta", (DL_FUNC) &_rtp_simpsonAdaBeta, 4},
    {"_rtp_riemannGamma", (DL_FUNC) &_rtp_riemannGamma, 4},
    {"_rtp_simpsonGamma", (DL_FUNC) &_rtp_simpsonGamma, 4},
    {"_rtp_tfisher", (DL_FUNC) &_rtp_tfisher, 5},
    {"_rtp_uniSel", (DL_FUNC) &_rtp_uniSel, 2},
    {"_rtp_simpleSel", (DL_FUNC) &_rtp_simpleSel, 2},
    {"_rtp_nth_element", (DL_FUNC) &_rtp_nth_element, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rtp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
