# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

baseNull <- function(x) {
    .Call(`_rtp_baseNull`, x)
}

init <- function(k, p) {
    .Call(`_rtp_init`, k, p)
}

betaSD <- function(a, b) {
    .Call(`_rtp_betaSD`, a, b)
}

fBetaD <- function(b) {
    .Call(`_rtp_fBetaD`, b)
}

fGammaD <- function(g) {
    .Call(`_rtp_fGammaD`, g)
}

fBetaQ <- function(p) {
    .Call(`_rtp_fBetaQ`, p)
}

fGammaQ <- function(p) {
    .Call(`_rtp_fGammaQ`, p)
}

fBetaDtop <- function() {
    .Call(`_rtp_fBetaDtop`)
}

rtpDbetaRiema <- function(k, p, tol = 1e-12, stepscale = 1) {
    .Call(`_rtp_rtpDbetaRiema`, k, p, tol, stepscale)
}

rtpDbetaAsimp <- function(k, p, abstol = 1e-7, reltol = 1e-3) {
    .Call(`_rtp_rtpDbetaAsimp`, k, p, abstol, reltol)
}

rtpDgammaRiema <- function(k, p, tol = 1e-12, stepscale = 1) {
    .Call(`_rtp_rtpDgammaRiema`, k, p, tol, stepscale)
}

rtpDgammaSimp <- function(k, p, tol = 1e-10, stepscale = 1) {
    .Call(`_rtp_rtpDgammaSimp`, k, p, tol, stepscale)
}

uniSel <- function(k, p) {
    .Call(`_rtp_uniSel`, k, p)
}

simpleSel <- function(k, p) {
    .Call(`_rtp_simpleSel`, k, p)
}

nth_element <- function(k, p) {
    .Call(`_rtp_nth_element`, k, p)
}

tfisher <- function(lw, L, tau1, tau2, tol = 1e-16) {
    .Call(`_rtp_tfisher`, lw, L, tau1, tau2, tol)
}

