# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fNull <- function(a) {
    .Call(`_rtp_fNull`, a)
}

init <- function(k, p) {
    .Call(`_rtp_init`, k, p)
}

betaSD <- function(a, b) {
    .Call(`_rtp_betaSD`, a, b)
}

dbetaHight <- function(a, b) {
    .Call(`_rtp_dbetaHight`, a, b)
}

fBetaD <- function(b) {
    .Call(`_rtp_fBetaD`, b)
}

fGammaD <- function(g) {
    .Call(`_rtp_fGammaD`, g)
}

fBetaQ <- function(p) {
    .Call(`_rtp_fBetaQ`, p)
}

fGammaQ <- function(p) {
    .Call(`_rtp_fGammaQ`, p)
}

fBetaDtop <- function() {
    .Call(`_rtp_fBetaDtop`)
}

probSmallest <- function(p) {
    .Call(`_rtp_probSmallest`, p)
}

fisher <- function(p) {
    .Call(`_rtp_fisher`, p)
}

riemannBeta <- function(k, p, tol = 1e-10, stepscale = 1) {
    .Call(`_rtp_riemannBeta`, k, p, tol, stepscale)
}

simpsonAdaBeta <- function(k, p, abstol = 1e-7, reltol = 1e-3) {
    .Call(`_rtp_simpsonAdaBeta`, k, p, abstol, reltol)
}

riemannGamma <- function(k, p, tol = 1e-10, stepscale = 1) {
    .Call(`_rtp_riemannGamma`, k, p, tol, stepscale)
}

simpsonGamma <- function(k, p, tol = 1e-10, stepscale = 1) {
    .Call(`_rtp_simpsonGamma`, k, p, tol, stepscale)
}

tfisher <- function(lw, n, tau1, tau2, tol = 1e-16) {
    .Call(`_rtp_tfisher`, lw, n, tau1, tau2, tol)
}

uniSel <- function(k, p) {
    .Call(`_rtp_uniSel`, k, p)
}

simpleSel <- function(k, p) {
    .Call(`_rtp_simpleSel`, k, p)
}

nth_element <- function(k, p) {
    .Call(`_rtp_nth_element`, k, p)
}

